### ISSUE TITLE
Zasto Native ?!

### ISSUE THREAD

**Issue by mokiding** [AmarKalabic/Gamers.ba-Mobile-app#1]
Zasto se je***\* sa native kada mozes da iskoristis html5,css3,js i napravis je multiplatform pomocu nekog SDK poput http://phonegap.com/

**Comment by AmarKalabic** [comment]
Svakako zanimljiv SDK s kojim se nisam susretao ranije, jesi voljan pomoći ako bi se prebacili na isti s obzirom da nikada prije nismo radili sa istim? A i vjerujem da bolje od nas poznaješ i html i css i js....
