### ISSUE TITLE
[Layout] Problem sa učitavanjem 

### ISSUE THREAD

**Issue by anelcolo** [AmarKalabic/Gamers.ba-Mobile-app#2]
Hej!

> Koristim Prestigio 5300 na 4.1.2 na kojemu je urađen ROOT. Pokrenem aplikaciju, učita se stranica, međum gornji dio stranice "header" bude isjeckana slika. U footeru je također problem, about je čitljiv, međutim bijela pozadina umjesto plave.
> 
> Dvije fotografije ubacujem kao prilog.

To je što sam ugrabio sad za sad da je problem.
### Header

![screenshot_2014-11-07-22-13-00](https://cloud.githubusercontent.com/assets/7916787/4960445/078c45bc-66c3-11e4-94a4-a7a6f7c7c574.png)
### Footer

![screenshot_2014-11-07-22-12-08](https://cloud.githubusercontent.com/assets/7916787/4960441/0272a558-66c3-11e4-90d7-557c14083947.png)

Znam da ovo nisu neki veliki problemi, ali čisto informativno radi.

**Comment by AmarKalabic** [comment]
Fixano zadnjim updateom. Hvala na prijavi!
